# Site settings
title: Инга Афанасьева
descriptor: Инга Афанасьева
baseurl: '' # the subpath of your site, e.g. /blog/
url: http://inga-doroga.ru # the base hostname & protocol for your site

author: Инга Афанасьева
email: ivan@dianov.org
phone: +7 905 332-50-17
skype: doroga12345

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

prose:
  # rooturl: "_posts"
  media: "media"
  siteurl: "http://dianov.org"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
